name: build

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install project
        run: |
          pip install git+https://github.com/vennelavarshini18/osmium.git@04797f2
          pip install .

      - name: Install test tools
        run: pip install pytest

      - name: Install markdown dependencies
        run: pip install markdown

      - name: Run tests
        run: pytest

      - name: Build site
        run: mobius build